version: 2

models:
    - name: fact_mx_crimes
      description: "This fact table aggregates crime data in Mexico at the municipal level. It serves as a central repository for crime-related information, allowing for in-depth analysis and reporting."
      columns:
        - name: crime_key
          data_type: string
          description: "Key field that uniquely identifies the crime incident."

        - name: entity_code
          data_type: string
          description: "The code representing the entity."

        - name: entity_name
          data_type: string
          description: "The name of the entity."

        - name: entity_name_short
          data_type: string
          description: "Short name of the entity."

        - name: municipality_code
          data_type: string
          description: "The code representing the municipality."

        - name: municipality_full_code
          data_type: string
          description: "The full code representing the municipality."

        - name: municipality_name
          data_type: string
          description: "The name of the municipality."

        - name: latitude
          data_type: float64
          description: "Latitude coordinates of the municipality."

        - name: longitude
          data_type: float64
          description: "Longitude coordinates of the municipality."

        - name: altitude
          data_type: float64
          description: "Altitude of the municipality."

        - name: affected_legal_asset
          data_type: string
          description: "Type of legal asset affected by the crime."

        - name: crime_type
          data_type: string
          description: "The type of crime."

        - name: crime_subtype
          data_type: string
          description: "The subtype of the crime."

        - name: crime_modality_type
          data_type: string
          description: "The modality type of the crime."

        - name: month_name
          data_type: string
          description: "The name of the month when the crime occurred."

        - name: month_nbr
          data_type: int64
          description: "The number representing the month when the crime occurred."

        - name: crimes
          data_type: int64
          description: "The number of crimes reported."

        - name: info_month_date
          data_type: date
          description: "The date of the month when the crime occurred."
