default:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT') }}"
      dataset: dez_project_mx_crimes
      threads: 4 # Must be a value of 1 or greater
      keyfile: "{{ env_var('CONTAINER_GCP_SECRET_FILE') }}"
      job_execution_timeout_seconds: 3000 # 50 mins
